<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;

Route::get('/deploy-fix-xyz789', function () {
    $output = [];

    $middlewareDir = base_path('app/Http/Middleware');
    $output[] = '=== FILES IN app/Http/Middleware ===';
    if (is_dir($middlewareDir)) {
        foreach (scandir($middlewareDir) as $f) {
            if ($f !== '.' && $f !== '..') {
                $output[] = '  ' . $f;
            }
        }
    } else {
        $output[] = 'DIRECTORY MISSING: ' . $middlewareDir;
    }

    $isAdminPath = base_path('app/Http/Middleware/IsAdmin.php');
    $isRegularPath = base_path('app/Http/Middleware/IsRegularUser.php');
    $output[] = '';
    $output[] = '=== FILE CHECK ===';
    $output[] = 'IsAdmin.php exists: ' . (file_exists($isAdminPath) ? 'YES' : 'NO');
    $output[] = 'IsRegularUser.php exists: ' . (file_exists($isRegularPath) ? 'YES' : 'NO');

    $output[] = '';
    $output[] = '=== AUTOLOAD REGENERATION ===';

    $composerPaths = [
        'composer',
        '/usr/local/bin/composer',
        '/usr/bin/composer',
        '/opt/cpanel/composer/bin/composer',
        base_path('composer.phar'),
    ];

    $phpBinaries = ['php', '/usr/local/bin/php', '/usr/bin/php', '/opt/cpanel/ea-php82/root/usr/bin/php', '/opt/cpanel/ea-php83/root/usr/bin/php'];

    $success = false;
    if (function_exists('shell_exec')) {
        $cwd = base_path();
        foreach ($composerPaths as $composer) {
            foreach ($phpBinaries as $php) {
                $cmd = "cd " . escapeshellarg($cwd) . " && $php $composer dump-autoload -o 2>&1";
                $result = shell_exec($cmd);
                if ($result && stripos($result, 'not found') === false && stripos($result, 'No such') === false) {
                    $output[] = "TRIED: $php $composer";
                    $output[] = $result;
                    $success = true;
                    break 2;
                }
            }
        }
        if (!$success) {
            $output[] = 'composer not found in standard locations - using manual fallback';
        }
    } else {
        $output[] = 'shell_exec disabled';
    }

    if (!$success) {
        $output[] = '';
        $output[] = '=== MANUAL CLASSMAP PATCH ===';
        $classmapPath = base_path('vendor/composer/autoload_classmap.php');
        if (file_exists($classmapPath) && file_exists($isAdminPath) && file_exists($isRegularPath)) {
            $classmap = require $classmapPath;
            $classmap['App\\Http\\Middleware\\IsAdmin'] = $isAdminPath;
            $classmap['App\\Http\\Middleware\\IsRegularUser'] = $isRegularPath;

            $export = "<?php\n\n// autoload_classmap.php @generated by Composer\n\n\$vendorDir = dirname(__DIR__);\n\$baseDir = dirname(\$vendorDir);\n\nreturn array(\n";
            foreach ($classmap as $class => $path) {
                $export .= "    " . var_export($class, true) . " => " . var_export($path, true) . ",\n";
            }
            $export .= ");\n";

            file_put_contents($classmapPath, $export);
            $output[] = 'Patched autoload_classmap.php with IsAdmin and IsRegularUser';

            $staticPath = base_path('vendor/composer/autoload_static.php');
            if (file_exists($staticPath)) {
                unlink($staticPath);
                $output[] = 'Deleted autoload_static.php (will be skipped, classmap loader will be used)';
            }
        } else {
            $output[] = 'Cannot patch - missing files';
        }
    }

    \Artisan::call('optimize:clear');
    $output[] = '';
    $output[] = '=== CACHE CLEAR ===';
    $output[] = \Artisan::output();

    foreach (['services.php', 'packages.php'] as $file) {
        $path = base_path('bootstrap/cache/' . $file);
        if (file_exists($path)) {
            unlink($path);
            $output[] = "deleted: bootstrap/cache/$file";
        }
    }

    $output[] = '';
    $output[] = '=== FINAL CHECK ===';
    $output[] = 'IsAdmin class loadable: ' . (class_exists(\App\Http\Middleware\IsAdmin::class) ? 'YES' : 'NO');
    $output[] = 'IsRegularUser class loadable: ' . (class_exists(\App\Http\Middleware\IsRegularUser::class) ? 'YES' : 'NO');

    return '<pre>' . implode("\n", $output) . '</pre>';
});

Route::get('/', fn() => redirect()->route('admin.login'));

// All SMS system routes under /sms prefix
Route::prefix('sms')->group(function () {
    Route::middleware('otp')->group(function () {
        // Regular users only
        Route::middleware('regular')->group(function () {
            Route::get('/home', fn() => view('home'))->name('home');
        });

        // Both roles
        Route::get('/tracking', fn() => view('admin.tracking'))->name('get.tracking');

        // Admin only
        Route::middleware('admin')->group(function () {
            Route::get('/users', fn() => view('admin.users.index'))->name('users.index');
            Route::get('/statistics', fn() => view('admin.statistics'))->name('statistics');
        });
    });

    Route::get('/', [LoginController::class, 'index'])->name('admin.login');
    Route::get('/login', fn() => redirect()->route('admin.login'));
    Route::get('/auth/redirect', [LoginController::class, 'redirectToProvider'])->name('auth.redirect');
    Route::get('/auth/callback', [LoginController::class, 'callback'])->name('auth.callback');
    Route::get('/logout', [LoginController::class, 'logout'])->name('admin.logout');
});
